### ISSUE TITLE
A quetion about the way MCU use the key

### ISSUE THREAD

**Issue by ZW18601702982** [yuugata/SHE_MemoryUpdateProtocol#2]
As you know ,if you wrap the Key in the format of M1-M5, you will load the M1-M3 to the key slot.
So how did the MCU use the key as a ciphertext? Or does the MCU decrypt the M1-M3 inside? 
I don't quite understand this , do you have a chance to share your point of view of this?Thanks for your attention.

**Comment by yuufyu** [comment]
The MCU decrypt the M1-M3 data.
This script can't decrypt M1-M3 to plain key(only encrypt plainkey to M1-M3).
Thank you.

**Comment by ZW18601702982** [comment]
OK, Got it. Thanks.
