### ISSUE TITLE
Wrong bitmask on key flags results in losing flag data

### ISSUE THREAD

**Issue by hexsecs** [yuugata/SHE_MemoryUpdateProtocol#5]
The key flags are using the wrong mask value, which results in incorrectly encoding flag data.
![image](https://user-images.githubusercontent.com/89217603/146134308-957b4ffc-39ef-4b0e-b603-6f709f826d6a.png)

**Comment by yuufyu** [comment]
Thank you for your PR. 
I merged it.

I think there is room for improvement on the API specification(including the existing).
I will try to consider it.
